### ISSUE TITLE
Support for Ruby 2.4.0

### ISSUE THREAD

**Issue by danielbayerlein** [rails/ruby-coffee-script#14]
Support for Ruby 2.4.0 would be great. At the moment it crashed. I'm not sure if the problem is the gem "coffee-script" or "therubyrace".

**Gemfile**

```gemfile
gem 'coffee-script'
```

**test.rb**

```ruby
require 'coffee_script'

CoffeeScript.compile File.read("script.coffee")
```

**Output**

```
/Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21: warning: constant ::Fixnum is deprecated
/Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `include': wrong argument type Class (expected Module) (TypeError)
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:23:in `block (2 levels) in <top (required)>'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `class_eval'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:22:in `block in <top (required)>'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `each'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8/conversion.rb:21:in `<top (required)>'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/therubyracer-0.12.2/lib/v8.rb:22:in `<top (required)>'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/ruby_racer_runtime.rb:108:in `available?'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `each'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `find'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:63:in `best_available'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:57:in `autodetect'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from /Users/danielbayerlein/.rbenv/versions/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from test.rb:1:in `<main>'
```

**Comment by matthewd** [comment]
> `therubyracer-0.12.2/lib/v8/conversion.rb`

That sounds rather a lot like the problem is not in this gem.

This gem uses [ExecJS](https://github.com/rails/execjs#execjs) to run the coffeescript compiler. Check that link for other runtimes you could use instead of therubyracer.

**Comment by danielbayerlein** [comment]
@matthewd Thank you for your feedback. You are right, `therubyracer` is currently not compatible with Ruby 2.4.0. https://github.com/cowboyd/therubyracer/issues/430

**Comment by sixtyfive** [comment]
The issue is closed as in, "we're not going to be supporting 2.4.0"?
